application: jyhjeff
version: 1
runtime: python27
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /step1.*
  script: step1.py

- url: /step2.*
  script: step2.py

- url: /step3.*
  script: step3.py

- url: /hello.*
  script: helloworld.py

- url: /sign.*
  script: helloworld.py

- url: /.*
  script: feedfetcher.py



